status = ["audit-ci-done", "rust-ci-done"]
timeout_sec = 43200                        # 12 hours
required_approvals = 1
delete_merged_branches = true
use_codeowners = false
up_to_date_approvals = false
