[package]
name = "jose"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
base64ct = { version = "1.5.0", default-features = false, features = ["alloc"] }
serde = { version = "1", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
hashbrown = { version = "0.12", default-features = true, features = ["serde"] }

[dev-dependencies]
rusty-hook = "0.11"
