[package]
name = "jose"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
std = ["signature/std", "thiserror-no-std/std"]

[dependencies]
thiserror-no-std = "2.0.2"
base64ct = { version = "1.5.0", default-features = false, features = ["alloc"] }
serde = { version = "1", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
hashbrown = { version = "0.12", features = ["serde"] }
hmac = { version = "0.12", default-features = false }
sha2 = { version = "0.10", default-features = false }
ed25519 = { version = "1", default-features = false, features = ["alloc"] }
ed25519-dalek = { version = "1", default-features = false, features = [
    "alloc",
    # FIXME: consider offering feature flags for other crypto backends
    "u64_backend",
] }
p256 = { version = "0.11", default-features = false, features = [
    "arithmetic",
    "ecdsa",
] }
# not useful yet
p384 = { version = "0.11", default-features = false, features = [
    "arithmetic",
    #"ecdsa",
] }
k256 = { version = "0.11.2", default-features = false, features = [
    "arithmetic",
] }
elliptic-curve = { version = "0.12", default-features = false, features = [
    "arithmetic",
    "jwk",
    "serde",
    "sec1",
    "pkcs8",
    "pem",
] }

rsa = { version = "0.7.0-pre", default-features = false }
digest = { version = "0.10", default-features = false, features = ["mac"] }
ecdsa = { version = "0.14", default-features = false, features = [
    "digest",
    "sign",
    "verify",
] }
signature = { version = "1.5.0", default-features = false }

# FIXME: remove this when we can use const generics
generic-array = { version = "0.14", default-features = false, features = [
    "serde",
] }

sec1 = { version = "0.3", default-features = false }
typenum = { version = "1.15", default-features = false, features = ["no_std"] }
num-traits = { version = "0.2.15", default-features = false }
num-bigint-dig = { version = "0.8.1", default-features = false, features = ["u64_digit"] }
serde-value = { version = "0.7.0", default-features = false }
