[package]
name = "jose"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
std = ["signature/std", "thiserror-no-std/std"]

[dependencies]
thiserror-no-std = "2.0.2"
base64ct = { version = "1.5.0", default-features = false, features = ["alloc"] }
serde = { version = "1", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
hashbrown = { version = "0.12", features = ["serde"] }
hmac = { version = "0.12", default-features = false }
sha2 = { version = "0.10", default-features = false }
ed25519 = { version = "1", default-features = false, features = ["alloc"] }
ed25519-dalek = { version = "1", default-features = false, features = [
    "alloc",
    # FIXME: consider offering feature flags for other crypto backends
    "u64_backend",
] }
p256 = { version = "0.11", default-features = false, features = ["arithmetic"] }
# not useful yet
p384 = { version = "0.10", default-features = false }
k256 = { version = "0.11.2", default-features = false, features = [
    "arithmetic",
] }
elliptic-curve = { version = "0.12", default-features = false, features = [
    "arithmetic",
] }

rsa = { version = "0.6", default-features = false }
digest = { version = "0.10", default-features = false, features = ["mac"] }
signature = { version = "1.5.0", default-features = false }
