[advisories]
version = 2

db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
  # There is no patch yet
  "RUSTSEC-2023-0071"
]

[licenses]
version = 2

# List of explictly allowed licenses, all other licenses are denied
allow = [
    "MIT",
    "Apache-2.0",
    # for unicode-ident crate
    "Unicode-DFS-2016",
    #   "Apache-2.0 WITH LLVM-exception",
    #   "MPL-2.0",
    "BSD-3-Clause",
    #   "BSD-2-Clause",
    #   "ISC",
    #   "CC0-1.0",
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
allow = []
deny = [
    { name = "ring", version = "*" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
