[graph]
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
    { id = "RUSTSEC-2023-0071", reason = "No fix available, see https://github.com/RustCrypto/RSA/issues/19 and https://github.com/RustCrypto/RSA/pull/394" },
]

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    # for unicode-ident crate
    "Unicode-3.0",
    "BSD-3-Clause",
    # For hashbrown dependency
    "Zlib",
    # OpenSSL / aws-lc
    "ISC",
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["ISC", "OpenSSL"], crate = "aws-lc-sys" },
]


[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
deny = [
    { name = "ring", version = "*" },
]
skip = [
    #"ansi_term@0.11.0",
    #{ crate = "ansi_term@0.11.0", reason = "you can specify a reason why it can't be updated/removed" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
# github.com organizations to allow git sources for
github = []
# gitlab.com organizations to allow git sources for
gitlab = []
# bitbucket.org organizations to allow git sources for
bitbucket = []
