[workspace]
changelog_path = "./CHANGELOG.md"
changelog_config = "cliff.toml"
pr_labels = ["release"]
pr_draft  = true
release_always = false

[[package]]
name = "jose"
publish_features = ["crypto-rustcrypto"]
